services:
  run_before:
    build:
      context: .
      dockerfile: Dockerfile
    command: go test -tags before  -v ./tests

  run_after:
    build:
      context: .
      dockerfile: Dockerfile
    command: go test -tags after -race -v ./tests

  evaluation:
    build:
      context: .
      dockerfile: Dockerfile
    command: go run evaluation/evaluation.go

