services:
  app-after:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - TS_NODE_PROJECT=tsconfig.after.json
    command: npm test

  app-before:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - TS_NODE_PROJECT=tsconfig.before.json
    command: npm test

  evaluation:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - TS_NODE_PROJECT=tsconfig.after.json
    command: npx ts-node evaluation/evaluation.ts
